// Tasks Actions

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';
export const FETCH_TASK_LIST = 'FETCH_TASK_LIST';
export const FETCH_TASK_LIST_START = 'FETCH_TASK_LIST_START';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAIL = 'FETCH_TASK_LIST_FAIL';
export const MODIFY_TASK = 'MODIFY_TASK';
export const MODIFY_TASK_START = 'MODIFY_TASK_START';
export const MODIFY_TASK_SUCCESS = 'MODIFY_TASK_SUCCESS';
export const MODIFY_TASK_FAIL = 'MODIFY_TASK_FAIL';
